apiVersion: v2
name: quarkus-adtech-demo
description: A Helm chart for deploying Quarkus AdTech Demo on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - quarkus
  - kafka
  - adtech
  - go
  - rust
maintainers:
  - name: 0xdant
home: https://github.com/0xdant/quarkus-adtech-demo
