[package]
name = "rust-receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.12.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.146"
rdkafka = "0.38.0"
tokio = { version = "1", features = ["full"] }
prometheus = "0.13"
lazy_static = "1.4"
