{{- if .Values.goReceiver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: go-receiver
  namespace: {{ .Values.namespace }}
  labels:
    app: go-receiver
    {{- include "quarkus-adtech-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  {{- if eq .Values.serviceType "NodePort" }}
  ports:
    - name: http
      port: {{ .Values.goReceiver.port }}
      targetPort: 8080
      nodePort: 30072
      protocol: TCP
  {{- else }}
  ports:
    - name: http
      port: {{ .Values.goReceiver.port }}
      targetPort: 8080
      protocol: TCP
  {{- end }}
  selector:
    app: go-receiver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-receiver
  namespace: {{ .Values.namespace }}
  labels:
    app: go-receiver
    {{- include "quarkus-adtech-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.goReceiver.replicas }}
  selector:
    matchLabels:
      app: go-receiver
  template:
    metadata:
      labels:
        app: go-receiver
    spec:
      containers:
        - name: go-receiver
          image: {{ .Values.goReceiver.image }}
          imagePullPolicy: {{ .Values.applicationImagePullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          resources:
            {{- toYaml .Values.goReceiver.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.goReceiver.healthCheck.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.goReceiver.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.goReceiver.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.goReceiver.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.goReceiver.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.goReceiver.healthCheck.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.goReceiver.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.goReceiver.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.goReceiver.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.goReceiver.healthCheck.failureThreshold }}
{{- end }}
