{{- if .Values.quarkusReceiver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: quarkus-receiver
  namespace: {{ .Values.namespace }}
  labels:
    app: quarkus-receiver
    {{- include "quarkus-adtech-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  {{- if eq .Values.serviceType "NodePort" }}
  ports:
    - name: http
      port: {{ .Values.quarkusReceiver.port }}
      targetPort: 8080
      nodePort: 30070
      protocol: TCP
  {{- else }}
  ports:
    - name: http
      port: {{ .Values.quarkusReceiver.port }}
      targetPort: 8080
      protocol: TCP
  {{- end }}
  selector:
    app: quarkus-receiver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-receiver
  namespace: {{ .Values.namespace }}
  labels:
    app: quarkus-receiver
    {{- include "quarkus-adtech-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.quarkusReceiver.replicas }}
  selector:
    matchLabels:
      app: quarkus-receiver
  template:
    metadata:
      labels:
        app: quarkus-receiver
    spec:
      containers:
        - name: quarkus-receiver
          image: {{ .Values.quarkusReceiver.image }}
          imagePullPolicy: {{ .Values.applicationImagePullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: QUARKUS_PROFILE
              value: "prod"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4317"
            - name: OTEL_SERVICE_NAME
              value: "quarkus-receiver"
          resources:
            {{- toYaml .Values.quarkusReceiver.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.quarkusReceiver.healthCheck.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.quarkusReceiver.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.quarkusReceiver.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.quarkusReceiver.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.quarkusReceiver.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.quarkusReceiver.healthCheck.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.quarkusReceiver.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.quarkusReceiver.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.quarkusReceiver.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.quarkusReceiver.healthCheck.failureThreshold }}
{{- end }}
